{
 "title": "formal",
 "time": { "from": "2024-07-28T04:00:00.000Z", "to": "2024-07-28T04:09:59.000Z" },
 "panels": [
  {
   "title": "UserCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"UserCount(1000,10)\")"
    },
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"UserCount(1000,100)\")"
    },
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"UserCount(500,100)\")"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"QPS(1000,10,[5,15])\")"
    },
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"QPS(1000,100,[5,15])\")"
    },
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"QPS(500,100,[5,15])\")"
    },
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"QPS(1000,10,[3,5])\")"
    }
   ]
  },
  {
   "title": "TotalRequests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"TotalRequests(1000,10,[5,15])\")"
    },
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"TotalRequests(1000,100,[5,15])\")"
    },
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"TotalRequests(500,100,[5,15])\")"
    },
    {
     "query": "from(bucket: \"formal\")\r\n  |> range(start: 2024-07-28T00:00:00Z)\r\n  |> filter(fn: (r) => r._measurement == \"TotalRequests(1000,10,[3,5])\")"
    }
   ]
  }
 ]
}